---

- name: "MediaWiki db configuration"
  hosts: mysql
  gather_facts: no
  tags: [ "mariadb", "mysql" ]
  roles:
    - role: "mediawiki/mariadb"

- name: "MediaWiki apache configuration"
  hosts: apache
  # one, all hosts
  serial: [ "1", "100%" ]
  tags: "apache"
  gather_facts: no
  roles:
    - role: "mediawiki/configuration"
