---

- name: "mediawiki database"
  mysql_db:
    name: "mediawiki"
    state: present

- name: "mediawiki user+privileges"
  mysql_user:
    name:     "{{mediawiki_db_user}}"
    password: "{{mediawiki_db_password}}"
    priv:     "mediawiki.*:ALL"
    state:    present
