---

- name: "Apache installation"
  hosts: inventaire
  tasks:
    - name: "Apache package installation"
      yum:
        name: "httpd"
        state: "present"
    - name: "Apache configuration"
      template:
        src: "inventaire.conf.j2"
        dest: "/etc/httpd/conf.d/inventaire.conf"
        owner: "apache"
        group: "apache"
    - name: "Start apache service"
      service:
        name: "httpd"
        state: "restarted"
        enabled: yes
      tags: [ "restart" ]
